import os


Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=''' 
	 $SECURITY_TRANSFORMS_HOME/libStructDiv/include 
	'''

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split( "StructDiv" )

# add cpp path
myenv=myenv.Clone(CPPPATH=Split(cpppath))


pgms="simple_sd_driver"
for i in Split(pgms):
	pgm=myenv.Program(target=i+".exe",  source=Split(i+".cpp"), LIBPATH=LIBPATH, LIBS=LIBS)
	install=myenv.Install("$SECURITY_TRANSFORMS_HOME/libStructDiv/test/", pgm)
	Default(install)


	
	
