import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

files="rewrite_util.cpp  transform.cpp"

cpppath='''
         $IRDB_SDK/include
         $SECURITY_TRANSFORMS_HOME/include
         $SECURITY_TRANSFORMS_HOME/libIRDB-core/include
         $SECURITY_TRANSFORMS_HOME/libIRDB-cfg/include
         $SECURITY_TRANSFORMS_HOME/libIRDB-util/include
         $SECURITY_TRANSFORMS_HOME/libMEDSannotation/include/
         $SECURITY_TRANSFORMS_HOME/third_party/capstone/include/capstone/
         $SECURITY_TRANSFORMS_HOME/third_party/keystone/include/keystone/
        '''


LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("irdb-core irdb-cfg irdb-util MEDSannotation capstone keystone")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CXXFLAGS = " -std=c++11 ")

lib=myenv.SharedLibrary("irdb-transform",  Split(files), LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)
Return('install')

