#!/usr/bin/env python

import sys
import os
import argparse
import beanstalk

'''
scoring job is:
score_job = {
	'id' : 'cbtest',
	'csid' : csid,
	'dir' : event['dir'],     # top level CGC event dir
	'component' : 'peasoup'   # who requested the job
	'executable_suffix'       : '.ps'                                             # optional 
	'ground_truth_poller_dir' : '<path to pollers>'                               # optional 
	'ground_truth_pov_dir'    : '<path to POVs>'                                  # optional 
	'techx_poller_dir'        : '<path to poller inputs as generated by TechX>'   # optional 
	'techx_pov_dir'           : '<path to POVs as generated by TechX>'            # optional 
}
'''

def submit_cbtest_job(b):
	j = {
		'id' : 'cbtest',
		'cbtest_id' : 100,
		'cb_name' : 'CROMU_00001',
                'cb_dir' : "/usr/share/cgc-sample-challenges/cqe-challenges/",
                'ps_extra_options': '--step-option zipr:\\\"--locality:on false\\\"',
	}
	print 'Submitting job: %s' % str(j)
	beanstalk.put_dict_priority(j, 0, b)

if __name__ == "__main__":
    b = beanstalk.connect_as_lead()
    submit_cbtest_job(b)
