import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=''' 
	 $IRDB_SDK/include 
	'''


files=Glob( Dir('.').srcnode().abspath+"/*.cpp")

myenv.Append(CPPFLAGS="-std=c++11")


pgm="dump_map.exe"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split( env.subst('$BASE_IRDB_LIBS')+ "  irdb-cfg irdb-util irdb-transform ") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
#install=myenv.Install("$SECURITY_TRANSFORMS_HOME/bin/", pgm)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", pgm)
Default(install)
Return('install')
