import os



Import('env')

# import and create a copy of the environment so we don't screw up anyone elses env.
myenv=env.Clone()

files=Glob( Dir('.').srcnode().abspath+"/*.cpp")

cpppath='''
	$IRDB_SDK/include 
	'''

myenv.Append(CPPPATH=Split(cpppath))



pgm="add_lib.exe"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("stars "+ myenv.subst('$BASE_IRDB_LIBS')+ " irdb-elfdep irdb-transform") 
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", pgm)
Default(install)
Return('install')
