import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=''' 
	 $IRDB_SDK/include 
	 $SECURITY_TRANSFORMS_HOME/include 
	 $SECURITY_TRANSFORMS_HOME/libIRDB/include 
	 $SECURITY_TRANSFORMS_HOME/libMEDSannotation/include 
	 $SECURITY_TRANSFORMS_HOME/libtransform/include
	 $SECURITY_TRANSFORMS_HOME/libEXEIO/include 
	'''


files=Glob( Dir('.').srcnode().abspath+"/*.cpp")

myenv.Append(CXXFLAGS = " -std=c++11 -Wall ")

pgm="selective_cfi.exe"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split( env.subst('$BASE_IRDB_LIBS')+ "  irdb-cfg irdb-util irdb-core irdb-transform MEDSannotation ") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", pgm)
Default(install)

ret=[]+install
	
	
#lib32=SConscript("zest_cfi_runtime/SConscript", variant_dir="build32")
if 'ZEST_RUNTIME' in os.environ: 
	zestcfi_lib=SConscript("zest_cfi_runtime/SConscript") # , variant_dir="build64")
	ret=ret+zestcfi_lib
Return('ret')
