env=Environment()
Export('env')

env.Replace(CFLAGS="-m64")
env.Replace(CCFLAGS="-m64")
env.Replace(INSTALL_PATH_PREFIX="$SECURITY_TRANSFORMS_HOME/appfw/lib/64")
SConscript("SConscript.64", variant_dir='build64')

env.Replace(CFLAGS="-m32")
env.Replace(CCFLAGS="-m32")
env.Replace(INSTALL_PATH_PREFIX="$SECURITY_TRANSFORMS_HOME/appfw/lib/32")
SConscript("SConscript.32", variant_dir='build32')
