import os

Import('env')
myenv=env
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])


libname="irdb-syscall"
files=  '''
	syscall.cpp
	'''
cpppath=''' 
	$IRDB_SDK/include/
	$SECURITY_TRANSFORMS_HOME/include/
	$SECURITY_TRANSFORMS_HOME/libIRDB-core/include/
	$SECURITY_TRANSFORMS_HOME/libIRDB-syscall/include/
	'''

#myenv.Append(CCFLAGS=" -Wall -W -Wextra -Wconversion ")

myenv.Append(CXXFLAGS = " -std=c++11 ")


myenv=myenv.Clone(CPPPATH=Split(cpppath))
lib=myenv.SharedLibrary(libname, Split(files), LIBS=Split("irdb-core irdb-util"), LIBPATH=Split("$SECURITY_TRANSFORMS_HOME/lib"))

install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)

Return('install')
