import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

files="elfdep.cpp"

cpppath='''
	 .
         $IRDB_SDK/include
         $SECURITY_TRANSFORMS_HOME/libIRDB/include
         $SECURITY_TRANSFORMS_HOME/libtransform/include
        '''


LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("irdb-core irdb-transform")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CXXFLAGS = " -std=c++11 ")

lib=myenv.SharedLibrary("irdb-elfdep",  Split(files), LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)

Return('install')
