import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

files="elfdep.cpp"

cpppath='''
         $SECURITY_TRANSFORMS_HOME/libIRDB/include
         $SECURITY_TRANSFORMS_HOME/libtransform/include
         $SECURITY_TRANSFORMS_HOME/libEXEIO/include/
         $SECURITY_TRANSFORMS_HOME/libMEDSannotation//include/
         $SECURITY_TRANSFORMS_HOME/libElfDep/include
        '''


LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("IRDB-core transform")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CXXFLAGS = " -std=c++11 ")

lib=myenv.Library("ElfDep",  Split(files), LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)

Return('install')
