import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

#files="integertransform32.cpp  integertransform64.cpp  integertransform.cpp  leapattern.cpp  pointercheck64.cpp  Rewrite_Utility.cpp  transform.cpp"
files="Rewrite_Utility.cpp  transform.cpp"

cpppath='''
         $SECURITY_TRANSFORMS_HOME/include
         $SECURITY_TRANSFORMS_HOME/libIRDB/include
         $SECURITY_TRANSFORMS_HOME/libtransform/include
         $SECURITY_TRANSFORMS_HOME/libMEDSannotation/include/
        '''


LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("IRDB-core IRDB-cfg IRDB-util MEDSannotation")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CXXFLAGS = " -std=c++11 ")

lib=myenv.SharedLibrary("transform",  Split(files), LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)
Return('install')

