import os



Import('irdb_env')

# import and create a copy of the environment so we don't screw up anyone elses env.
myenv=irdb_env.Clone()

cpppath=myenv['IRDB_INC']
files=Glob( Dir('.').srcnode().abspath+"/*.cpp")

pgm="add_lib.exe"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("stars "+ myenv.subst('$BASE_IRDB_LIBS')+ " irdb-elfdep irdb-transform") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", pgm)
Default(install)
Return('install')
