import os

print "In libIRDB/tests/SConscript"


Import('env')
env.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=''' 
	 $SECURITY_TRANSFORMS_HOME/include 
	 $SECURITY_TRANSFORMS_HOME/libIRDB/include 
	 $SECURITY_TRANSFORMS_HOME/libMEDSannotation/include 
	 $SECURITY_TRANSFORMS_HOME/beaengine/include 
	 $SECURITY_TRANSFORMS_HOME/tools/transforms 
	'''


files=Glob("*.cpp")

pgm="fill_in_safefr.exe"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("IRDB-core IRDB-cfg IRDB-util pqxx BeaEngine_s_d rewrite MEDSannotation") 
env=env.Clone(CPPPATH=Split(cpppath))
pgm=env.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
install=env.Install("$SECURITY_TRANSFORMS_HOME/bin/", pgm)
env.Alias("install", "$SECURITY_TRANSFORMS_HOME/bin/")
Default(install)

	
	
