import os


env=Environment()
Export('env')
lib=SConscript("SConscript")


pedi = Command( target = "./testoutput",
                source = "./SConscript",
                action = "cd "+os.environ['SECURITY_TRANSFORMS_HOME']+" ; " + os.environ['PEDI_HOME']+"/pedi -m manifest.txt ; cd - " )

Depends(pedi,lib);
Default(pedi)

