import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=''' 
	 $SECURITY_TRANSFORMS_HOME/include 
	 $SECURITY_TRANSFORMS_HOME/libehp/include 
	 $SECURITY_TRANSFORMS_HOME/libEXEIO/include 
	 $SECURITY_TRANSFORMS_HOME/libcapstone/include 
	'''


files=Glob( Dir('.').srcnode().abspath+"/*.cpp")


pgm="rida.exe"

LIBPATH=Split('''
	$SECURITY_TRANSFORMS_HOME/lib 
	$SECURITY_TRANSFORMS_HOME/libcapstone
	''')
LIBS=Split("ehp EXEIO pebliss capstone") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", pgm)
Default(install)

Return('install')
