import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=''' 
	 $SECURITY_TRANSFORMS_HOME/include 
	 $SECURITY_TRANSFORMS_HOME/xform
	 $SECURITY_TRANSFORMS_HOME/libIRDB/include 
	 $SECURITY_TRANSFORMS_HOME/libMEDSannotation/include 
	 $SECURITY_TRANSFORMS_HOME/beaengine/include 
	 $SECURITY_TRANSFORMS_HOME/tools/transforms 
	'''

files=Glob( Dir('.').srcnode().abspath+"/*.cpp")


pgm="meds2pdb"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("IRDB-core IRDB-cfg IRDB-util pqxx xform BeaEngine_s_d rewrite MEDSannotation pq pq ") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
Default(myenv.Install("$SECURITY_TRANSFORMS_HOME/bin/", pgm))
Default(myenv.Install("$SECURITY_TRANSFORMS_HOME/tools/meds2pdb/", pgm))

	
	
