import os

Import('env')
myenv=env.Clone()


LIBS= " irdb-cfg irdb-transform irdb-core EXEIO "

cpppath='''
        $IRDB_SDK/include
	$PEASOUP_HOME/irdb-libs/libEXEIO/include
        '''

libpath="$SECURITY_TRANSFORMS_HOME/lib"
myenv.Append(LIBPATH=Split(libpath))
myenv.Append(CPPPATH=Split(cpppath))




all_files="P1_utility.cpp PNTransformDriver.cpp PNStackLayout.cpp PNRange.cpp Range.cpp OffsetInference.cpp DirectOffsetInference.cpp ScaledOffsetInference.cpp P1Inference.cpp PNRegularExpressions.cpp PNMain.cpp StackLayout.cpp General_Utility.cpp AnnotationBoundaryGenerator.cpp PrecedenceBoundaryInference.cpp PNIrdbManager.cpp EhUpdater.cpp"

p1=myenv.SharedLibrary("p1transform.so", Split(all_files), LIBS=Split(LIBS))
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", p1)
Default(install)

Return('install')
