import os

Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])


libname="EXEIO"
files=  '''
	exeio_src.cpp
	'''

cpppath=''' 
	.
	$SECURITY_TRANSFORMS_HOME/include/
	$SECURITY_TRANSFORMS_HOME/libEXEIO/include
	$SECURITY_TRANSFORMS_HOME/pebliss/trunk/pe_lib/
	'''


myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CXXFLAGS=" -std=c++11 -Wall -Werror ")
lib=myenv.Library(libname, Split(files))

install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)

Return('install')
