import os

Import('env')
myenv=env
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])


libname="EXEIO"
files=  '''
	exeio_src.cpp
	'''

cpppath=''' 
	.
	$SECURITY_TRANSFORMS_HOME/include/
	$SECURITY_TRANSFORMS_HOME/libEXEIO/include
	$SECURITY_TRANSFORMS_HOME/pebliss/trunk/pe_lib/
	'''

#myenv.Append(CCFLAGS="-Wp,-w -Wall")
myenv.Append(CCFLAGS="-w")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
lib=myenv.Library(libname, Split(files))

install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)

