import os


Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=''' 
	 $SECURITY_TRANSFORMS_HOME/include 
	 $SECURITY_TRANSFORMS_HOME/libIRDB/include 
	 $SECURITY_TRANSFORMS_HOME/libEXEIO/include 
	 $SECURITY_TRANSFORMS_HOME/tools/transforms
	 $SECURITY_TRANSFORMS_HOME/xform
	 $SECURITY_TRANSFORMS_HOME/libMEDSannotation/include
	'''

#	 $SECURITY_TRANSFORMS_HOME/libtransform/include 
CPPFLAGS="--std=c++11"
LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split( env.subst('$BASE_IRDB_LIBS')+ "IRDB-core IRDB-cfg IRDB-util pqxx rewrite BeaEngine_s_d transform MEDSannotation")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
myenv.Append(CPPFLAGS=CPPFLAGS)

pgm=myenv.Program(target="fix_canaries.exe", source=Split("fix_canaries.cpp fix_canaries_driver.cpp"), LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", pgm)
Default(install)
Return('install')
