import os

Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

lib="MEDSannotation"

files=  '''
	src/FuncExitAnnotation.cpp
	src/MEDS_AnnotationParser.cpp
	src/MEDS_FPTRShadowAnnotation.cpp
	src/MEDS_DeadRegAnnotation.cpp
	src/MEDS_FRSafeAnnotation.cpp
	src/MEDS_FuncPrototypeAnnotation.cpp
	src/MEDS_InstructionCheckAnnotation.cpp
	src/MEDS_ProblemFuncAnnotation.cpp
	src/MEDS_Register.cpp
	src/MEDS_SafeFuncAnnotation.cpp
	src/VirtualOffset.cpp
	'''
cpppath=''' 
	./include/
	'''

#CFLAGS="-fPIC  "

myenv=myenv.Clone(CPPPATH=Split(cpppath))
lib=myenv.Library(lib, Split(files))

install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)
Return('install')
