import os


Import('irdb_env')
myenv=irdb_env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=irdb_env['IRDB_INC'] + " $SECURITY_TRANSFORMS_HOME/third_party/elfio-code/ "
LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split( myenv.subst('$BASE_IRDB_LIBS') + " irdb-core irdb-cfg irdb-util irdb-transform MEDSannotation")

if 'debug' in myenv and int(myenv['debug']) == 1:
        print "Setting debug mode in resolve_callbacks"
        myenv.Append(CFLAGS=" -g -O0")
        myenv.Append(CXXFLAGS=" -g -O0")
        myenv.Append(LINKFLAGS=" -g -O0")

myenv=myenv.Clone(CPPPATH=Split(cpppath))

pgm=myenv.Program(target="resolve_callbacks.exe", source=Split("callbacks.cpp callbacks_driver.cpp"), LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", pgm)
Default(install)
Return('install')
