
Import('env')
myenv=env.Clone()


cpppath=" $IRDB_SDK/include $SECURITY_TRANSFORMS_HOME/third_party/elfio-code/ "
libpath="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split( " irdb-core irdb-cfg irdb-util irdb-transform ")


myenv.Append(LIBPATH=Split(libpath))
myenv.Append(CPPPATH=Split(cpppath))

pgm=myenv.Program(target="resolve_callbacks.exe", source=Split("callbacks.cpp callbacks_driver.cpp"), LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", pgm)
Default(install)
Return('install')
