import os

Import('env')
myenv=env
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])


libname="IRDB-syscall"
files=  '''
	syscall.cpp
	'''
cpppath=''' 
	$SECURITY_TRANSFORMS_HOME/include/
	$SECURITY_TRANSFORMS_HOME/libIRDB/include/
	$SECURITY_TRANSFORMS_HOME/beaengine/include
	$SECURITY_TRANSFORMS_HOME/beaengine/beaengineSources/Includes/
	'''

#myenv.Append(CCFLAGS=" -Wall -W -Wextra -Wconversion ")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
lib=myenv.Library(libname, Split(files))

install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)

Return('install')
