import os

Import('env')
env.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])


libname="IRDB-syscall"
files=  '''
	syscall.cpp
	'''
cpppath=''' 
	$SECURITY_TRANSFORMS_HOME/include/
	$SECURITY_TRANSFORMS_HOME/libIRDB/include/
	$SECURITY_TRANSFORMS_HOME/beaengine/include
	$SECURITY_TRANSFORMS_HOME/beaengine/beaengineSources/Includes/
	'''

env['CCFLAGS'].append(Split("-Wall -W -Wextra -Wconversion "))

env=env.Clone(CPPPATH=Split(cpppath))
lib=env.Library(libname, Split(files))

install=env.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
env.Alias("install", "$SECURITY_TRANSFORMS_HOME/lib/")

Default(install)

