import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=''' 
	 $SECURITY_TRANSFORMS_HOME/include 
	 $SECURITY_TRANSFORMS_HOME/libIRDB/include 
	 $SECURITY_TRANSFORMS_HOME/libMEDSannotation/include 
	 $SECURITY_TRANSFORMS_HOME/beaengine/include 
	 $SECURITY_TRANSFORMS_HOME/tools/transforms 
	'''

myenv.Append(CCFLAGS=" -DCGC")

files=Glob( Dir('.').srcnode().abspath+"/*.cpp")


pgm="watch_syscall.exe"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split("IRDB-core IRDB-cfg IRDB-syscall IRDB-util pqxx BeaEngine_s_d transform rewrite MEDSannotation") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/bin/", pgm)
myenv.Alias("install", "$SECURITY_TRANSFORMS_HOME/bin/")
Default(install)



