import os

Import('env')

dirs='''
	transforms
	cover
	fix_rets
	meds2pdb
	memcover
	ret_shadow_stack
	safefr
	safefn
	selective_cfi
	simple_cdi
	spasm
	watch_syscall
	cookbook
	dump_map
	print_cfi_stats
	'''
cgc_dirs='''
	c2e
	cgc_hlx
	cgclibc
	cgc_rigrandom
	cinderella
	inferfn
	prince
	'''


for i in Split(dirs):
	SConscript(os.path.join(i,"SConscript"))


if 'build_cgc' in env and int(env['build_cgc']) == 1:
	for i in Split(cgc_dirs):
		SConscript(os.path.join(i,"SConscript"))
