import os

Import('env')

tools=[]

dirs='''
	transforms
	cover
	fix_rets
        meds2pdb	
	ret_shadow_stack
	safefr
	selective_cfi
	simple_cdi
	spasm
	cookbook
	dump_map
	hook_start
	'''

nobuild_dirs='''
	print_cfi_stats
	memcover
	'''
cgc_dirs='''
	c2e
	cgc_hlx
	cgclibc
	cgc_rigrandom
	cinderella
	inferfn
	prince
	'''


for i in Split(dirs):
	newtool=SConscript(os.path.join(i,"SConscript"))
	tools=tools + newtool


if 'build_cgc' in env and int(env['build_cgc']) == 1:
	for i in Split(cgc_dirs):
		newtool=SConscript(os.path.join(i,"SConscript"))
		tools=tools+newtool

Return('tools')
