import os

Import('env')
env.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

files=  '''
	./beaengineSources/BeaEngine.c
	'''
cpppath=''' 
	./include/
	./beaengineSources/Includes/
	'''


# inherit from above.
#CFLAGS="-fPIC  -pedantic -ansi -pipe -fno-common -fshort-enums -g -Wall -W -Wextra -Wconversion -Wno-long-long -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings"
#CC="gcc"
#env=env.Clone(CC=CC, CPPPATH=Split(cpppath), CFLAGS=CFLAGS)


env=env.Clone(CPPPATH=Split(cpppath))
lib=env.Library("BeaEngine_s_d", Split(files))

install=env.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
env.Alias("install", "$SECURITY_TRANSFORMS_HOME/lib/")

Default(install)

