import os

Import('env')

myenv=env.Clone();
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

files=  '''
	$SECURITY_TRANSFORMS_HOME/beaengine/beaengineSources/BeaEngine.c
	'''
cpppath=''' 
	$SECURITY_TRANSFORMS_HOME/beaengine/include/
	$SECURITY_TRANSFORMS_HOME/beaengine/beaengineSources/Includes/
	'''

#print 'myenv[cflags]='+str(myenv['CFLAGS'])
#print 'myenv=\n'
#print myenv.Dump()
myenv=myenv.Clone(CPPPATH=Split(cpppath))
lib=myenv.Library("BeaEngine_s_d", Split(files))

install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)

