import os

Import('env')

myenv=env.Clone();
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

files=  '''
	./beaengineSources/BeaEngine.c
	'''
cpppath=''' 
	./include/
	./beaengineSources/Includes/
	'''
myenv=myenv.Clone(CPPPATH=Split(cpppath))
lib=myenv.Library("BeaEngine_s_d", Split(files))

install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
Default(install)

