import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])

cpppath=''' 
	 $IRDB_SDK/include 
	 $SECURITY_TRANSFORMS_HOME/libIRDB-core/include 
	'''


files=Glob( Dir('.').srcnode().abspath+"/*.cpp")

myenv.Append(CXXFLAGS = " -std=c++11 -Wall ")

pgm="thanos.exe"

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split( env.subst('$BASE_IRDB_LIBS')+ " irdb-transform dl") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
pgm=myenv.Program(pgm,  files,  LIBPATH=LIBPATH, LIBS=LIBS)
install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install", pgm)
Default(install)

	
	

ret=[]+install
Return('ret')
