import os

Import('env')
env.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])


libname="IRDB-core"
files=  '''
	address.cpp
	baseobj.cpp
	dbinterface.cpp
	file.cpp
	fileir.cpp
	function.cpp
	generate_spri.cpp
	icfs.cpp
	instruction.cpp
	instrution.cpp
	pqxxdb.cpp
	type.cpp
	variantid.cpp
	'''
cpppath=''' 
	.
	$SECURITY_TRANSFORMS_HOME/include/
	$SECURITY_TRANSFORMS_HOME/libIRDB/include/
	$SECURITY_TRANSFORMS_HOME/beaengine/include
	$SECURITY_TRANSFORMS_HOME/beaengine/beaengineSources/Includes/
	'''

CFLAGS="-fPIC  -Wall -W -Wextra -Wconversion "
CC="g++"

env=env.Clone(CC=CC, CPPPATH=Split(cpppath), CFLAGS=CFLAGS)
lib=env.Library(libname, Split(files))

install=env.Install("$SECURITY_TRANSFORMS_HOME/lib/", lib)
env.Alias("install", "$SECURITY_TRANSFORMS_HOME/lib/")

Default(install)

