import os
import glob

Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])


libname="IRDB-core"
files=  '''
	address.cpp
	baseobj.cpp
	dbinterface.cpp
	file.cpp
	fileir.cpp
	function.cpp
	generate_spri.cpp
	icfs.cpp
	instruction.cpp
	pqxxdb.cpp
	type.cpp
	scoop.cpp
	variantid.cpp
	eh.cpp
	reloc.cpp
	decode_cs.cpp
	operand_cs.cpp
	decode_bea.cpp
	operand_bea.cpp
	decode_meta.cpp
	operand_meta.cpp
	'''

cpppath=''' 
	.
	$SECURITY_TRANSFORMS_HOME/include/
	$SECURITY_TRANSFORMS_HOME/libIRDB/include/
	$SECURITY_TRANSFORMS_HOME/beaengine/include
	$SECURITY_TRANSFORMS_HOME/beaengine/beaengineSources/Includes/
	$SECURITY_TRANSFORMS_HOME/libcapstone/include/
	'''

globs=glob.glob(os.environ['SECURITY_TRANSFORMS_HOME']+'/libcapstone/zipr_unpack/*.o')

myenv.Append(CCFLAGS=" -std=c++11 ")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
mylib=myenv.Library(libname, Split(files) + globs)

install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", mylib)
Default(install)

Return('install')

