import os

Import('env')
myenv=env
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])


libname="IRDB-core"
files=  '''
	address.cpp
	baseobj.cpp
	dbinterface.cpp
	file.cpp
	fileir.cpp
	function.cpp
	generate_spri.cpp
	icfs.cpp
	instruction.cpp
	pqxxdb.cpp
	type.cpp
	variantid.cpp
	'''
cpppath=''' 
	.
	$SECURITY_TRANSFORMS_HOME/include/
	$SECURITY_TRANSFORMS_HOME/libIRDB/include/
	$SECURITY_TRANSFORMS_HOME/beaengine/include
	$SECURITY_TRANSFORMS_HOME/beaengine/beaengineSources/Includes/
	'''

myenv.Append(CCFLAGS=" -Wall -W -Wextra -Wconversion ")

myenv=myenv.Clone(CPPPATH=Split(cpppath))
mylib=myenv.Library(libname, Split(files))

install=myenv.Install("$SECURITY_TRANSFORMS_HOME/lib/", mylib)
Default(install)

