.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH man 1 "31 Mar 2000"
.SH NAME
cexport \- create header file with exported declarations from a C file
.SH SYNOPSIS
.B cexport
.RB "[\| " \-c
.IR cpp\-command " \|]"
.RB "[\| " \-e
.IR extension " \|]"
.RB "[\| " \-h " \|]"
.RI "[\| " cc\-options " \|]"
.RI "[\| " file " [\| " file... " \|] \|]"
.SH DESCRIPTION
[ToDo]
