.TH man 1 "2 Dec 1998"
.SH NAME
count \- count elements and attributes in HTML or XML files files
.SH SYNOPSIS
.B count
.RB "[\| " file " \|]"
.SH DESCRIPTION
.LP
The
.B count
command counts the number of elements and attributes of each type that
appears in the input and prints a report on stdout.
.SH OPERANDS
The following operand is supported:
.TP 10
.I file
The name of an HTML or XML file. If absent, standard input is read
instead.
.SH "EXIT STATUS"
The following exit values are returned:
.TP 10
.B 0
Successful completion.
.TP
.B >0
An error occurred in the parsing of the HTML or XML file.
.B count
will try to recover from the error and produce output anyway.
.SH BUGS
.LP
None known. Don't trust the output if there were errors in the input.
