.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH man 1 "31 Mar 2000"
.SH NAME
htmlprune \- remove marked elements from an HTML file
.SH SYNOPSIS
.B htmlprune
.RB "[\| " \-c
.IR class " \|]"
.RB "[\| " \-x " \|]"
.RI "[\| " file " \|]"
.SH DESCRIPTION
.B htmlprune
removes specially marked elements (with their content and children)
from an HTML file. By default it removes elements with a class
attribute of "exclude". The class attribute is parsed as a
whitespace-separated list of words and if one of those words is
"exclude", the element is not copied to the output.
.PP
The option
.B \-c
can be used to specify a different word than "exclude". The option
.B \-x
forces output to be in XML-style, i.e., without short attributes and
with a slash (/) to mark empty elements.
.PP
[ToDo]
