.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH man 1 "31 Mar 2000"
.SH NAME
multitoc \- create a table of content for a set of HTML files
.SH SYNOPSIS
.B multitoc
.RB "[\| " \-x " \|]"
.RB "[\| " \-s
.IR preample " \|]"
.RB "[\| " \-e
.IR postample " \|]"
.RB "[\| " \-l
.IR low
.RB " | " \-h
.IR high
.RB " | " \-b
.IR base
.RB " | " \-c
.IR configfile
.RI " | " file " \|] ..."
.SH DESCRIPTION
[ToDo]
