.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH man 1 "2 Dec 1998"
.SH NAME
toc \- insert a table of contents in an HTML file
.SH SYNOPSIS
.B toc
.RB "[\| " \-x " \|]"
.RB "[\| " \-l
.IR low " \|]"
.RB "[\| " \-h
.IR high " \|]"
.RB "[\| " file " \|]"
.RB "[\| " \-t " \|]"
.SH DESCRIPTION
.LP
The
.B toc
command reads an HTML file, inserts ID attributes in all H1 to H6 that
don't have one already, and also inserts A elements with NAME
attributes, so old browsers will recognize the H1 to H6 headers as
target anchors as well. The output is written to stdout.
.LP
If there is a comment of the form
.d
<!\-\-toc\-\->
.e
or a pair of comments
.d
<!\-\-begin-toc\-\->
<!\-\-end-toc\-\->
.e
then the comment, or the pair with everything in between will be
replaced by a table of contents, consisting of a list (UL) of links to
all headers in the document.
.LP
If a header has a CLASS attribute with as value (or one of its values)
the keyword "no-toc", then that header will not appear in the table
of contents.
.SH OPTIONS
The following options are supported:
.TP 10
.B \-x
Use XML conventions: empty elements are written with a slash at the
end: <IMG\ />
.TP
.BI \-l " low"
Sets the lowest numbered header to appear in the table of
content. Default is 1 (i.e., H1).
.TP
.BI \-h " high"
Sets the highest numbered header to appear in the table of
content. Default is 6 (i.e., H6).
.TP
.B \-t
Normally,
.B toc
adds both ID attributes and empty A elements with a NAME attribute and
CLASS="bctarget", so that older browsers that do no understand ID will
still find the target. With this option, the A elements will not be
generated.
.SH OPERANDS
The following operand is supported:
.TP 10
.I file
The name of an HTML file. If absent, standard input is read instead.
.SH "EXIT STATUS"
The following exit values are returned:
.TP 10
.B 0
Successful completion.
.TP
.B >0
An error occurred in the parsing of the HTML file.
.B toc
will try to correct the error and produce output anyway.
.SH "SEE ALSO"
.BR num (1),
.BR normalize (1),
.BR xml2asc (1)
.BR asc2xml (1)
.SH BUGS
.LP
The error recovery for incorrect HTML is primitive.
