.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH man 1 "31 July 1999"
.SH NAME
wls \- list links in an HTML file
.SH SYNOPSIS
.B wls
.RB "[\| " \-l " \|]"
.RB "[\| " \-r " \|]"
.RB "[\| " \-h " \|]"
.RB "[\| " \-b
.IR " base" " \|]"
.RB "[\| " file " \|]"
.SH DESCRIPTION
.LP
The
.B wls
command reads an HTML file (standard input by default) and prints out
all links it finds. The output is written to stdout.
.SH OPTIONS
The following options are supported:
.TP 10
.B \-l
Produce a long listing. Instead of just the URI,
.B wls
prints three columns: the element name, the value of the REL
attribute, and the URI.
.TP
.BI \-r
Print relative URLs as they are, without converting them to absolute
URLs.
.TP
.BI \-b " base"
Use
.I base
as the initial base URL. If there is a <base> element in the document, 
it will override the -b option.
.TP
.BI \-h
Output as HTML. The output will be listed in the form of <a> elements.
.SH OPERANDS
The following operands are supported:
.TP 10
.I file
The name or the URL of an HTML file. If absent, standard input is read instead.
.SH "EXIT STATUS"
The following exit values are returned:
.TP 10
.B 0
Successful completion.
.TP
.B >0
An error occurred in the parsing of the HTML file.
.B toc
will try to correct the error and produce output anyway.
.SH "SEE ALSO"
.BR num (1),
.BR normalize (1),
.BR xml2asc (1)
.BR asc2xml (1)
.SH BUGS
.LP
None known yet.
