.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH man 1 "31 Mar 2000"
.SH NAME
xml2asc \- convert UTF8 to &#nnn; entities
.SH SYNOPSIS
.B xml2asc
.SH DESCRIPTION
.LP
Reads a UTF-8 encoded text from standard input and writes to standard
output, converting all non-ASCII characters to &#nnn; entities, so
that the result is ASCII-encoded.
.LP
One example use is to convert ISO-8859-1 to ASCII with &#nnn;
entities, by first running
.B asc2xml
to convert ISO-8859-1 to UTF-8 and the pipe the result into
.B xml2asc
to convert to ASCII with &#nnn; entities for all accented characters.
.SH "SEE ALSO"
.BR asc2xml (1),
.BR UTF-8
(RFC 2279)
.SH BUGS
.LP
Doesn't distinguish mark-up from content, so if the input uses
non-ASCII characters in XML element names, they will be output with
numerical entities in them, which is not legal in XML.
