.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH man 1 "31 Mar 2000"
.SH NAME
xmlns \- replace XML Namespace prefixes by "global names"
.SH SYNOPSIS
.B xmlns
.RB "[\| " \-d " \|]"
.RB "[\| " \-\- " \|]"
.RI "[\| " file " \|]"
.SH DESCRIPTION
.B xmlns
expands all element and attribute names to "global names" by expanding
the prefix. All names will be printed as "{URL}name". Attribute names
without a prefix will have an empty namespace part: "{}name". The
namespace attributes (those that start with "xmlns") will be removed.
.PP
By default comments, PIs and the doctype declaration are removed, but
with option
.B \-d
they are kept unchanged.
.PP
[ToDo]
