.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH man 1 "4 Aug 2000"
.SH NAME
xref \- generate cross-references inside and between HTML files
.SH SYNOPSIS
.B xref
.RB "[\| " \-x " \|]"
.RB "[\| " \-b
.IR base " \|]"
.RB "[\| " \-i
.IR index " \|]"
.RI "[\| -- \|] [\| " input " [\| " output " \|] \|]"
.SH DESCRIPTION
.LP
The
.B xref
command links inline elements to DFN elements with the same content.
It adds ID attributes where necessary. If the content of a DFN or
other element isn't suitable, the TITLE attribute may be used to
provide the term to use for comparisons.
.LP
Here is an example:
.d
<p>A <dfn>b-box</dfn> is defined to be...
<p>For every b there is a <em>b-box</em>...
.e
The output of
.B xref
will be similar to this:
.d
<p>A <dfn id="b-box">b-box</dfn> is defined to be...
<p>For every b there is a <em><a href="#b-box">b-box<a/></em>...
.e
.SH OPTIONS
The following options are supported:
.TP 10
.B \-x
Use XML conventions: empty elements are written with a slash at the
end: <IMG\ />
.TP
.BI \-b " base"
Sets the prefix for the generated URLs. By default
.I base
is empty, which generates URLs like "#b-box" above. If
.I base
is set to, e.g., "http://xyz/", the URLs will look like
"http://xyz/#b-box".
.TP
.BI \-i " index"
Directs
.I xref
to read terms from a database file before looking for them in the
document and afterwards store the terms that were found in the same
file. DFN element in the document ovrride terms found in
.IR index "."
This allows
.I xref
to be run multiple times on different files, to make the files refer
to each other. It may be necessary to run the commands twice, to
resolve all cross-references.
.SH OPERANDS
The following operands are supported:
.TP 10
.I input
The name of an HTML file. If absent, standard input is read instead.
The special name "-" also indicates standard input. The
.I input
may be a URL.
.TP
.I output
The file to write to. If absent, standard output is used. This may
.I not
be a URL.
.SH "EXIT STATUS"
The following exit values are returned:
.TP 10
.B 0
Successful completion.
.TP
.B >0
An error occurred in the parsing of the HTML file.
.B toc
will try to correct the error and produce output anyway.
.SH "SEE ALSO"
.BR index (1),
.BR num (1),
.BR toc (1),
.BR normalize (1),
.BR xml2asc (1)
.BR asc2xml (1)
.SH BUGS
.LP
The error recovery for incorrect HTML is primitive.
.LP
The program generates ID attributes, but doesn't generate <a name=...>
tags, so the links only work in browsers that recognize ID attributes.
