import os



Import('env')
myenv=env.Clone()
myenv.Replace(SECURITY_TRANSFORMS_HOME=os.environ['SECURITY_TRANSFORMS_HOME'])
myenv.Replace(IRDB_SDK=os.environ['IRDB_SDK'])

cpppath=''' 
	 $IRDB_SDK/include 
	'''

myenv.Append(CPPFLAGS="-std=c++11")

LIBPATH="$SECURITY_TRANSFORMS_HOME/lib"
LIBS=Split( " irdb-core irdb-cfg irdb-util irdb-transform ") 
myenv=myenv.Clone(CPPPATH=Split(cpppath))
dm=myenv.Program("dump_map.exe", Split("dump_map.cpp"),  LIBPATH=LIBPATH, LIBS=LIBS)
dm_install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", "dump_map.exe")

dehp=myenv.Program("dump_ehp.exe", Split("dump_ehp.cpp"),  LIBPATH=LIBPATH, LIBS=LIBS)
dehp_install=myenv.Install("$SECURITY_TRANSFORMS_HOME/plugins_install/", "dump_ehp.exe")

all=list() + dm_install + dehp_install


Default(all)
Return('all')
